import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Acid's Blog",
  description: "Generated by create next app",
};

export { RootLayout as default } from "@/app/layouts/root-layout";
